# Generated by Django 6.0.5 on 2026-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='prioity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
