# Generated by Django 6.0.5 on 2026-06-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_created_at_task_created_at_task_prioity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prioity',
            new_name='priority',
        ),
    ]
