# Generated by Django 6.0.5 on 2026-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_prioity_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='priority_choices',
        ),
        migrations.AddField(
            model_name='task',
            name='category_choices',
            field=models.CharField(choices=[('Study', 'Study'), ('Work', 'Work'), ('Personal', 'Personal')], default='Study', max_length=10),
        ),
    ]
